script:
  - id: checkforstop
    mode: restart                   
    then:
    - logger.log: "script CheckForStop running"
    - delay: 2s
    - if:
        condition:
          binary_sensor.is_off: footswitch
        then:          
            - logger.log: "stop mode detected"  
            - switch.turn_off: fastmotor            
            - switch.turn_off: slowmotor               
     

binary_sensor:
  - platform: gpio
    name: "Footswitch"  
    id: footswitch
    pin: 
      number: GPIO13
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 10ms
    on_press:    
      then:

    on_release:
       then:
        - script.execute: checkforstop
        - if:
            condition:
              switch.is_on: fastmotor        
            then:
              - switch.turn_off: fastmotor            
              - switch.turn_on: slowmotor            
            else:    
              - switch.turn_on: fastmotor            
              - switch.turn_off: slowmotor           

switch:
  - platform: gpio
    id: fastmotor
    pin: GPIO14
#    inverted: True

    interlock: [slowmotor]

  - platform: gpio
    id: slowmotor
    pin: GPIO12
    interlock: [fastmotor]

esphome:
  name: leslie-flip-flop-footswitch
  friendly_name: Leslie Flip Flop footswitch
  on_boot:
    then:  
      - switch.turn_on: slowmotor
      - switch.turn_off: fastmotor

esp8266:
   board: esp01_1m
# esp32:
#   variant: ESP32C3
#   board: esp32-c3-devkitm-1
#   framework:
#     type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:


ota:
  - platform: esphome

wifi:
  reboot_timeout: 0s
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Leslie-Flip-Flop-Footswitch"
    password: !secret wifi_password

captive_portal:
    