script:
  - id: checkforstop
    mode: restart                   
    then:
    - logger.log: "script CheckForStop running"
    - delay: 2s
    - if:
        condition:
          binary_sensor.is_off: footswitch
        then:          
            - logger.log: "STOP MODE ON"  
            - switch.turn_on: stop                
            - switch.turn_off: fastmotor            
            - switch.turn_off: slowmotor               
            - switch.turn_off: led         
               

binary_sensor:
  - platform: gpio
    name: "Footswitch"  
    id: footswitch
    pin: 
      number: GPIO13
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 200ms
    # on_press:    
    #   then:
    #    - switch.turn_on: led

    on_release:
       then:
        - script.execute: checkforstop
#coming out of stop,ALWAYS go to SLOW mode              

        - if:
            condition:
              - and: 
                - switch.is_on: fastmotor              
                - switch.is_off: stop
            then:
              - logger.log: "SLOW MODE" 
              - switch.turn_off: fastmotor 
              - switch.turn_off: led      
              - delay: 100ms      
              - switch.turn_on: slowmotor                         
            else:           
              - logger.log: "FAST MODE" 
              - switch.turn_off: slowmotor
              - delay: 250ms
              - switch.turn_on: fastmotor             
              - switch.turn_on: led

        - if:
            condition:
              - and: 
                - switch.is_on: stop
            then:
              - logger.log: "SLOW MODE" 
              - switch.turn_off: fastmotor 
              - switch.turn_off: led            
              - switch.turn_on: slowmotor                         
              - switch.turn_off: stop


#d1/gpio5 d2/gpio4 best for relays
switch:
  - platform: gpio
    id: fastmotor
    pin: GPIO4
#    inverted: true
    interlock: [slowmotor]
 
  - platform: gpio
    id: slowmotor
    pin: GPIO5
#    inverted: true
    interlock: [fastmotor]

  - platform: gpio #onboard led
    id: led
    pin: GPIO2
    inverted: True

  - platform: gpio
    id: stop
    pin: GPIO12

esphome:
  name: leslie-flip-flop-footswitch
  friendly_name: Leslie Flip Flop footswitch
  on_boot:
    then:  
      - wifi.disable:
      - switch.turn_on: slowmotor
      - switch.turn_off: fastmotor
      - switch.turn_off: led
esp8266:
   board: esp01_1m
# esp32:
#   variant: ESP32C3
#   board: esp32-c3-devkitm-1
#   framework:
#     type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:


ota:
  - platform: esphome

wifi:
  enable_on_boot: false
  reboot_timeout: 0s
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ap_timeout: 0s
    ssid: "Leslie-Flip-Flop-Footswitch"
    password: !secret wifi_password

captive_portal:    
